[env]
RUST_BACKTRACE = "1"

[jobs.simple]
command = ["cargo", "run", "--", "800,5"]
need_stdout = true
allow_failures = true
allow_warnings = true

[jobs.cli]
command = ["cargo", "run", "--", "--help"]
need_stdout = true
allow_failures = true
allow_warnings = true
